# Generated by Django 5.1.7 on 2025-03-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_team_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
